sudo: true
language: go

go:
  - "1.10"

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y libpgm-dev curl make git libtool automake build-essential dh-autoreconf pkg-config mercurial dh-autoreconf

install:
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout 0.4.5
  - ./autogen.sh
  - ./configure && make check
  - sudo make install
  - sudo ldconfig
  - cd ..
  - curl -L -o ./zeromq.tar.gz https://github.com/zeromq/libzmq/releases/download/v4.2.5/zeromq-4.2.5.tar.gz
  - tar -C . -zxvf ./zeromq.tar.gz
  - rm ./zeromq.tar.gz
  - cd zeromq-4.2.5
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - go get github.com/pebbe/zmq4
  - go get github.com/FLAGlab/gyre/zre/msg
  - go get github.com/FLAGlab/gyre/beacon
  - go get golang.org/x/net/ipv4
  - go get golang.org/x/net/ipv6
  - go get github.com/armen/goviral/zgossip
  - go build -a
  - sudo ifconfig
  - uname -a

env: ZSYS_INTERFACE=lo

script:
 - go test -v . ./beacon ./zre/msg ./shm
