language: go

go:
  - 1.2
  - 1.3

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y curl make git libtool build-essential dh-autoreconf pkg-config mercurial dh-autoreconf

install:
  - curl -o ./zeromq.tar.gz http://download.zeromq.org/zeromq-4.0.4.tar.gz
  - tar -C . -zxvf ./zeromq.tar.gz
  - rm ./zeromq.tar.gz
  - cd zeromq-4.0.4
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
  - go get github.com/pebbe/zmq4
  - go get github.com/zeromq/gyre/zre/msg
  - go get -u github.com/zeromq/gyre/beacon
  - go get code.google.com/p/go.net/ipv4
  - go get code.google.com/p/go.net/ipv6
  - go build -a
  - sudo ifconfig
  - uname -a

env: ZSYS_INTERFACE=lo

script:
 - go test -v . ./beacon ./zre/msg ./shm
